remove hardcoded delegator emissions percentage
helium/helium-program-library pull request #106
Opened 2023-03-14 02:50 UTC by ThornM9

2023-03-14 14:34 UTC, bryzettler approved these changes

2023-03-14 14:34 UTC, bryzettler commented on packages/helium-cli/src/create-subdao.ts
> +    default: 6,
Do we want this defaulted to 6 or just a required field on the script?

2023-03-20 21:47 UTC, ChewingGlass requested changes

2023-03-20 21:47 UTC, ChewingGlass commented on packages/helium-cli/src/create-subdao.ts
> +    describe: "Percentage of rewards allocated to delegators. Must be between 0-100 and can have 2 decimal places.",
This is wrong?

2023-03-20 21:47 UTC, ChewingGlass commented on packages/helium-cli/src/update-subdao.ts
> +    describe: "Percentage of rewards allocated to delegators. Must be between 0-100 and can have 2 decimal places.",
again, not right

2023-03-20 21:47 UTC, ChewingGlass commented on programs/helium-sub-daos/src/instructions/initialize_sub_dao_v0.rs
> +        .checked_mul(10_u64.checked_pow(8_u32).unwrap())
burning compute, prefer `10_00000000`

2023-03-20 21:47 UTC, ChewingGlass commented on programs/helium-sub-daos/src/instructions/initialize_sub_dao_v0.rs
> +  assert!(
`require_lt!` will give a better error

2023-03-20 21:47 UTC, ChewingGlass commented on programs/helium-sub-daos/src/instructions/issue_rewards_v0.rs
> +    .checked_mul(10_u64.checked_pow(8_u32).unwrap())
same as above

2023-03-20 21:47 UTC, ChewingGlass commented on programs/helium-sub-daos/src/instructions/issue_rewards_v0.rs
> +      .checked_div(max_percent) // 100% with 2 decimals accuracy
comment is wrong

2023-03-20 21:47 UTC, ChewingGlass commented on programs/helium-sub-daos/src/instructions/update_sub_dao_v0.rs
> +    assert!(delegator_rewards_percent < max_percent);
same as above

2023-03-20 21:47 UTC, ChewingGlass commented on tests/utils/daos.ts
> +      delegatorRewardsPercent: new BN(6 * Math.pow(10, 8)), // 6%
Should make a helper function for this. Ex `delegatorRewardsPercent(10.25666)`

2023-03-21 22:13 UTC, ChewingGlass approved these changes

2023-03-21 22:13 UTC, merged