Feature/account postgres sink
helium/helium-program-library pull request #124
Opened 2023-03-28 19:46 UTC by bryzettler

2023-03-28 22:08 UTC, ChewingGlass requested changes

2023-03-28 22:08 UTC, ChewingGlass commented on packages/account-postgres-sink-service/Dockerfile
> +RUN npm prun --production
npm prun lol

2023-03-28 22:08 UTC, ChewingGlass commented on packages/account-postgres-sink-service/package.json
> +    "angry-purple-tiger": "^1.0.5",
Doesn't seem like it needs all these deps

2023-03-29 03:54 UTC, ThornM9 approved these changes

2023-03-29 03:54 UTC, ThornM9 commented on packages/account-postgres-sink-service/src/utils/santizeAccount.ts
Typo in file name

2023-03-29 19:54 UTC, ChewingGlass commented on packages/account-postgres-sink-service/src/server.ts
> +          table: "sub_dao_epoc_info",
Can we just make this all a YAML config? And have one endpoint that causes a re-trigger on all tables. The endpoints helius will be hitting won't be structured like this anyway.

2023-03-29 19:54 UTC, ChewingGlass commented on packages/account-postgres-sink-service/src/server.ts
> +          table: "sub_dao_epoc_info",
I'd rather not have to re push docker containers to change this config

2023-03-29 20:15 UTC, bryzettler commented on packages/account-postgres-sink-service/src/utils/upsertProgramAccounts.ts
> +              [Op.ne]: sequelize.fn("NOW"),
Is it? they're both in the same transaction I assumed the would be the same now

2023-03-30 14:00 UTC, ChewingGlass approved these changes

2023-03-30 14:00 UTC, merged