Implement Mobile carriers and subscribers as rewardable entities (#263)
helium/helium-program-library pull request #264
Opened 2023-05-16 22:56 UTC by ChewingGlass

2023-05-18 17:16 UTC, bryzettler approved these changes

2023-05-18 17:16 UTC, bryzettler commented on programs/helium-entity-manager/src/instructions/issue_program_entity_v0.rs
> +      collection_authority_record_pda: self.bubblegum_program.to_account_info(),
why is this the bubblegum_program?

2023-05-22 01:35 UTC, ThornM9 requested changes

2023-05-23 16:30 UTC, ChewingGlass commented on programs/helium-entity-manager/src/state.rs
> +  pub key_serialization: KeySerialization,
Nope

2023-05-23 23:10 UTC, ThornM9 approved these changes

2023-05-24 20:22 UTC, merged